# -*- coding: utf-8 -*-
"""Cópia de Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqmuae6u_unlunlvbiD_Rx-8C938DbU6
"""

import this
this.num1 = 0
this.num2 = 0
this.opcao = -1 #Declaração de variáveis globais
this.tabNum1 = ""
this.tabNum2 = ""

def coletar():
  this.num1 = int(input("Informe um número: "))
  this.num2 = int(input("Informe outro número: "))

def somar():
  return f"A soma de {this.num1} + {this.num2} = {this.num1 + this.num2}"

def subtrair():
  return f"A subtração de {this.num1} - {this.num2} = {this.num1 - this.num2}"

def dividir():
  if(this.num2 != 0):
    return f"A divisão de {this.num1} / {this.num2} = {this.num1 / this.num2}"
  else:
    return f"Impossível dividir por zero!"

def multiplicar():
  return f"A multiplicação de {this.num1} * {this.num2} = {this.num1 * this.num2}"

def tabuada():
  for i in range(0,11,1): #(inicio,qtde repetições,contagem) | i = contador
    this.tabNum1 += f"{this.num1} * {i} = {this.num1 * i}\n"
    this.tabNum2 += f"{this.num2} * {i} = {this.num2 * i}\n"
  return f"Tabuada do {this.num1}: \n{this.tabNum1} \n\n Tabuada do {this.num2}: \n{this.tabNum2}"

def menu():
  while(this.opcao != 0):
    this.opcao = int(input("\n\n\n0. Sair\n1. Somar\n2. Subtrair\n3. Dividir\n4. Multiplicar\n5. Tabuada\nEscolha uma das opções acima: "))
    if(this.opcao == 0):
      print("Obrigado!")
    elif(this.opcao == 1):
      coletar()
      print(somar())
    elif(this.opcao == 2):
      coletar()
      print(subtrair())
    elif(this.opcao == 3):
      coletar()
      print(dividir())
    elif(this.opcao == 4):
      coletar()
      print(multiplicar())
    elif(this.opcao == 5):
      coletar()
      print(tabuada())
    else:
      print("Erro! Código escolhido não existe!")

#Chamar o método menu
menu()